version: "3.8"
services:
  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      - user-svc
      - product-svc

  user-svc:
    build: ./user-svc

  product-svc:
    build: ./product-svc
