server {
    listen 80;

    location /site1/ {
        proxy_pass http://web1/;
    }

    location /site2/ {
        proxy_pass http://web2/;
    }

    location / {
        return 200 'Nginx Reverse Proxy Demo\n';
        add_header Content-Type text/plain;
    }
}
