split_clients "${remote_addr}${http_user_agent}" $version {
    80% v1;
    * v2;
}

upstream v1 {
    server app-v1:3000;
}

upstream v2 {
    server app-v2:3000;
}

server {
    listen 80;
    location / {
        proxy_pass http://$version;
        proxy_set_header Host $host;
        add_header X-Deployed-Version $version;
    }
}
