pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'docker build -t jenkins-demo .'
            }
        }
        stage('Test') {
            steps {
                echo '运行测试...'
            }
        }
        stage('Deploy') {
            steps {
                sh 'docker run -d -p 3001:3000 jenkins-demo'
            }
        }
    }
}
