version: "3.8"
services:
  prometheus:
    build: .
    ports:
      - "9090:9090"
    volumes:
      - prom_data:/prometheus

  app:
    build: ./app
    ports:
      - "3000:3000"

volumes:
  prom_data:
