print("=" * 40)
print("  容器化基础教程")
print("=" * 40)
print("1. 镜像(Image): 只读模板")
print("2. 容器(Container): 镜像的运行实例")
print("3. 仓库(Registry): 存储镜像")
print("4. Dockerfile: 构建镜像的脚本")
print("=" * 40)
print("演示运行成功!")
